USE [CARSM];
GO

GRANT SELECT, INSERT, UPDATE
ON OBJECT::dbo._CONFIG TO [OR\calin];

GRANT SELECT, INSERT, UPDATE
ON OBJECT::dbo._VEHICLES TO [OR\calin];

GRANT SELECT, INSERT, UPDATE
ON OBJECT::dbo._INSPECTIONS TO [OR\calin];
GO